services:
  monitoring-api:
    build: .
    container_name: monitoring-api

    ports:
      - "${HOST_PORT:-4001}:${PORT:-4001}"

    env_file:
      - .env

    volumes:
      - "${HOST_PUSH_NOTIFICATION_DB}:${PUSH_NOTIFICATION_DB}"
      - "${HOST_BLOG_DB}:${BLOG_DB}"
      - "${HOST_HUGO_POST_PATH}:${HUGO_POST_PATH}"
      - "${HOST_BLOG_ASSETS_PATH}:${BLOG_ASSETS_PATH}"

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:${PORT:-4001}/api/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
